export enum SonosCommands {
  AdvancedCommand = 'adv-command',
  Command = 'command',
  JoinGroup = 'joingroup',
  LeaveGroup = 'leavegroup',
  Mute = 'mute',
  Next = 'next',
  Notify = 'notify',
  Pause = 'pause',
  Play = 'play',
  PlayMode = 'playmode',
  Previous = 'previous',
  Queue = 'queue',
  Seek = 'seek',
  SelectTrack = 'selecttrack',
  SetTransportUri = 'setavtransporturi',
  Sleep = 'sleep',
  Speak = 'speak',
  Stop = 'stop',
  Toggle = 'toggle',
  Unmute = 'unmute',
  Volume = 'volume',
  VolumeDown = 'volumedown',
  VolumeUp = 'volumeup'
}
